runtime: python37

env_variables:
    REDIS_HOST: 10.208.174.147
    REDIS_PORT: 6379

network:
  name: "projects/apollo-server-273118/global/networks/default"

vpc_access_connector:
  name: "projects/apollo-server-273118/locations/us-central1/connectors/cache-connector"

